services:
    esa_team_speak:
        class: eSA\TeamSpeakBundle\Service\TeamSpeak3Api
        lazy: true
        arguments:
            - "%esa_team_speak.host"
            - "%esa_team_speak.port%"
            - "%esa_team_speak.query_port%"
            - "%esa_team_speak.username%"
            - "%esa_team_speak.password%"
            - "%esa_team_speak.nickname%"
            - "%esa_team_speak.timeout%"