services:
    esa_team_speak:
        class: eSA\TeamSpeakBundle\Service\TeamSpeak3Api
        lazy: true
        arguments:
            - "%sn_team_speak3.host%"
            - "%sn_team_speak3.port%"
            - "%sn_team_speak3.query_port%"
            - "%sn_team_speak3.username%"
            - "%sn_team_speak3.password%"
            - "%sn_team_speak3.nickname%"
            - "%sn_team_speak3.timeout%"